
import { Book, Video, Artist, Audio, Category, Article } from './types';

export const CATEGORIES: Category[] = ['All', 'History', 'Philosophy', 'Culture', 'Arts', 'Biography', 'Buddhism'];
export const VIDEO_CATEGORIES = ['All', 'Documentary', 'Performance', 'Interview', 'Shorts'];
export const AUDIO_CATEGORIES = ['All', 'Symphony', 'Instrumental', 'Vocal', 'Podcast'];

export const ARTICLES: Article[] = [
  {
    id: 'art-1',
    title: 'The Resonance of Ancient Music',
    titleZh: '古乐的共鸣',
    titleKh: 'សំឡេងនៃតន្ត្រីបុរាណ',
    excerpt: 'Exploring how traditional Chinese musical instruments like the Erhu and Pipa connect modern audiences.',
    excerptZh: '探讨二胡、琵琶等中国传统乐器如何将现代观众联系在一起。',
    author: 'Elena Wong',
    authorZh: '王艾琳',
    date: '2024-05-15',
    readTime: '8 min',
    imageUrl: 'https://images.unsplash.com/photo-1516280440614-6697288d5d38?auto=format&fit=crop&w=800&q=80',
    category: 'Arts',
    views: 3200
  },
  {
    id: 'art-2',
    title: 'Confucian Values in the Digital Age',
    titleZh: '数字时代的儒家价值观',
    titleKh: 'តម្លៃខុងជឺក្នុងយុគសម័យឌីជីថល',
    excerpt: 'Can ancient wisdom regarding filial piety guide our interactions in a hyper-connected world?',
    excerptZh: '关于孝道的古老智慧能否指导我们在高度互联的世界中的互动？',
    author: 'Dr. Liang Chen',
    authorZh: '陈亮博士',
    date: '2024-05-10',
    readTime: '12 min',
    imageUrl: 'https://images.unsplash.com/photo-1524230572899-a752b3835840?auto=format&fit=crop&w=800&q=80',
    category: 'Philosophy',
    views: 4500
  }
];

export const BOOKS: Book[] = [
  {
    id: 'book-analects-confucius',
    title: 'The Analects',
    titleZh: '论语',
    titleKh: 'អាណាលេក',
    author: 'Confucius',
    authorZh: '孔子',
    category: 'Philosophy',
    categoryZh: '哲学',
    year: '475 BC',
    coverUrl: 'https://images.unsplash.com/photo-1589182373726-e4f658ab50f0?auto=format&fit=crop&w=600&q=80',
    description: 'A collection of sayings and ideas attributed to the Chinese philosopher Confucius.',
    descriptionZh: '记录孔子及其弟子言行的语录集。',
    pages: 350,
    views: 12500,
    fileSize: '4.5 MB',
    pdfUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf'
  },
  {
    id: 'book-analects-lau',
    title: 'The Analects',
    titleZh: '论语 (刘译)',
    titleKh: 'អាណាលេក (D.C. Lau)',
    author: 'D. C. Lau',
    authorZh: '刘殿爵',
    category: 'History',
    categoryZh: '历史',
    year: '1979',
    coverUrl: 'https://images.unsplash.com/photo-1512428559087-560fa5ceab42?auto=format&fit=crop&w=600&q=80',
    description: 'A critical translation of the core Confucian text by the renowned scholar D.C. Lau.',
    descriptionZh: '由著名学者刘殿爵教授翻译的儒家核心文献。',
    pages: 280,
    views: 8400,
    fileSize: '3.8 MB',
    pdfUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf'
  },
  {
    id: 'book-tao-te-ching',
    title: 'Tao Te Ching',
    titleZh: '道德经',
    titleKh: 'តាវតឺជីង',
    author: 'Laozi',
    authorZh: '老子',
    category: 'Philosophy',
    categoryZh: '哲学',
    year: '400 BC',
    coverUrl: 'https://images.unsplash.com/photo-1621351183012-e2f9972dd9bf?auto=format&fit=crop&w=600&q=80',
    description: 'A fundamental text for both philosophical and religious Taoism.',
    descriptionZh: '道家哲学思想的重要来源。',
    pages: 81,
    views: 9800,
    fileSize: '2.1 MB',
    pdfUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf'
  },
  {
    id: 'book-art-of-war',
    title: 'Art of War',
    titleZh: '孙子兵法',
    titleKh: 'សិល្បៈសង្គ្រាម',
    author: 'Sun Tzu',
    authorZh: '孙武',
    category: 'Philosophy',
    categoryZh: '哲学',
    year: '500 BC',
    coverUrl: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&w=600&q=80',
    description: 'An ancient Chinese military treatise attributed to Sun Tzu.',
    descriptionZh: '世界上最早的兵书之一。',
    pages: 50,
    views: 30500,
    fileSize: '1.5 MB',
    pdfUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf'
  }
];

export const AUDIOS: Audio[] = [
  {
    id: 'aud-1',
    title: 'Divine Mercy',
    titleZh: '慈悲的展现',
    artist: 'Shen Yun Symphony',
    artistZh: '神韵交响乐团',
    category: 'Symphony',
    categoryZh: '交响乐',
    coverUrl: 'https://images.unsplash.com/photo-1514320298324-a4a278ea605f?auto=format&fit=crop&w=500&q=60',
    duration: '04:15',
    date: '2024-05-12',
    plays: 5420,
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3'
  }
];

export const VIDEOS: Video[] = [
  {
    id: 'vid-1',
    title: 'Understanding Culture',
    titleZh: '理解传统文化',
    thumbnailUrl: 'https://images.unsplash.com/photo-1514533240710-2856035caee9?auto=format&fit=crop&w=800&q=80',
    duration: '15:30',
    category: 'Documentary',
    categoryZh: '纪录片',
    views: 12000,
    date: '2024-05-14',
    presenter: 'Prof. Zhang',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4'
  }
];

export const ARTIST_PROFILES: Artist[] = [
  {
    id: 'art-cf',
    name: 'Confucius',
    nameZh: '孔子',
    nameKh: 'ខុងជឺ',
    role: 'Philosopher',
    roleZh: '哲学家',
    roleKh: 'ទស្សនវិទូ',
    bio: 'Chinese philosopher and politician of the Spring and Autumn period. The philosophy of Confucius, also known as Confucianism, emphasized personal and governmental morality, correctness of social relationships, justice, kindness, and sincerity.',
    bioZh: '春秋时期的中国哲学家和政治家。孔子的哲学（也称为儒家思想）强调个人和政府的道德、社会关系的正确性、正义、善良和真诚。',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Confucius_Analects_Project_Gutenberg.jpg/300px-Confucius_Analects_Project_Gutenberg.jpg',
    code: 'CF',
    bookCount: 1,
    views: 15420
  },
  {
    id: 'art-lz',
    name: 'Laozi',
    nameZh: '老子',
    nameKh: 'ឡៅជឺ',
    role: 'Philosopher',
    roleZh: '哲学家',
    roleKh: 'ទស្សនវិទូ',
    bio: 'Ancient Chinese philosopher and writer, renowned author of the Tao Te Ching and the founder of philosophical Taoism.',
    bioZh: '中国古代哲学家和作家，著名的《道德经》作者和道家哲学的创始人。',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Zhang_Lu-Laozi_Riding_an_Ox.jpg/300px-Zhang_Lu-Laozi_Riding_an_Ox.jpg',
    code: 'LZ',
    bookCount: 1,
    views: 9800
  },
  {
    id: 'art-st',
    name: 'Sun Tzu',
    nameZh: '孙武',
    nameKh: 'ស៊ុន អ៊ូ',
    role: 'Military Strategist',
    roleZh: '军事家',
    roleKh: 'អ្នកយុទ្ធសាស្ត្រយោធា',
    bio: 'Chinese general, military strategist, writer, and philosopher who lived in the Eastern Zhou period. Sun Tzu is traditionally credited as the author of The Art of War.',
    bioZh: '中国东周时期的将军、军事家、作家和哲学家。孙武被认为是《孙子兵法》的作者。',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/2/23/Encho_Sun_Tzu.jpg',
    code: 'ST',
    bookCount: 1,
    views: 30500
  },
  {
    id: 'art-sy',
    name: 'Shen Yun Symphony',
    nameZh: '神韵交响乐团',
    nameKh: 'វង់តន្រ្តី សិន យុន',
    role: 'Orchestra',
    roleZh: '交响乐团',
    roleKh: 'វង់តន្រ្តី',
    bio: 'Shen Yun Symphony Orchestra blends the spirit of Chinese music with the power of a Western orchestra.',
    bioZh: '神韵交响乐团将中国音乐的精神与西方管弦乐团的力量完美结合。',
    imageUrl: 'https://www.shenyun.com/data/image/original/2021/05/29/600x400_20210529124403759567.jpg',
    code: 'SY',
    audioCount: 1,
    views: 5420
  },
  {
    id: 'art-dl',
    name: 'D. C. Lau',
    nameZh: '刘殿爵',
    nameKh: 'D. C. Lau',
    role: 'Sinologist',
    roleZh: '汉学家',
    roleKh: 'អ្នកប្រាជ្ញ',
    bio: 'D.C. Lau was a renowned sinologist and translator of Chinese classics, best known for his translations of the Tao Te Ching, the Analects, and Mencius.',
    bioZh: '刘殿爵是一位著名的汉学家和中国典籍翻译家，以翻译《道德经》、《论语》和《孟子》而闻名。',
    imageUrl: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=300&q=80',
    code: 'DL',
    bookCount: 1,
    views: 8400
  },
  {
    id: 'art-ew',
    name: 'Elena Wong',
    nameZh: '王艾琳',
    nameKh: 'Elena Wong',
    role: 'Musicologist',
    roleZh: '音乐学家',
    roleKh: 'អ្នកតន្ត្រីវិទ្យា',
    bio: 'Expert in traditional Asian instruments and their modern adaptations.',
    bioZh: '传统亚洲乐器及其现代改编专家。',
    imageUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=300&q=80',
    code: 'EW',
    articleCount: 1,
    views: 3200
  },
  {
    id: 'art-pz',
    name: 'Prof. Zhang',
    nameZh: '张教授',
    nameKh: 'សាស្ត្រាចារ្យ Zhang',
    role: 'Historian',
    roleZh: '历史学家',
    roleKh: 'ប្រវត្តិវិទូ',
    bio: 'Professor of Ancient Chinese History and Culture, specializing in the Tang Dynasty.',
    bioZh: '中国古代历史文化教授，主攻唐代历史。',
    imageUrl: 'https://images.unsplash.com/photo-1568602471122-7832951cc4c5?auto=format&fit=crop&w=300&q=80',
    code: 'PZ',
    videoCount: 1,
    views: 12000
  }
];

export const UI_STRINGS = {
  en: {
    home: 'Home',
    books: 'Books',
    articles: 'Articles',
    multimedia: 'Multimedia',
    about: 'About',
    authors: 'Authors',
    login: 'Member',
    donate: 'Donate',
    library: 'Library',
    audioLibrary: 'Audio Library',
    heroSub: 'Discovering the essence of 5000 years of civilization, history, and wisdom through Insight Sharing.',
    searchPlaceholder: 'Search by title or author...',
    readOnline: 'READ ONLINE',
    viewDetails: 'View Details',
    totalCollection: 'Total Collection',
    loadMore: 'Load More',
    listenNow: 'Listen Now',
    contactUs: 'Contact Us',
    synopsis: 'Synopsis',
    bookDetails: 'Book Details',
    aiLibrarian: 'AI Librarian',
    totalTracks: 'Tracks',
    all: 'All',
    history: 'History',
    philosophy: 'Philosophy',
    culture: 'Culture',
    arts: 'Arts',
    biography: 'Biography',
    buddhism: 'Buddhism',
    donateHeader: 'Support Insight Sharing',
    donateDesc: 'Your contribution helps us preserve five millennia of wisdom and bring it to a global audience.',
    oneTime: 'One-time',
    monthly: 'Monthly',
    customAmount: 'Custom Amount',
    leaveMessage: 'Leave a message (Optional)',
    next: 'Next',
    raised: 'Raised',
    goal: 'Goal',
    backers: 'Backers',
    artistProfile: 'Artist Profile',
    artistCode: 'Code',
    audioAlbums: 'Audio Albums',
    bookAlbums: 'Book Collections',
    videoAlbums: 'Video Collections',
    totalInteractions: 'Total Plays/Reads',
    mostPopular: 'Most Popular Contributions',
    audio: 'Audio',
    videos: 'Videos',
    none: 'None available',
    welcomeBack: 'Welcome Back',
    loginSub: 'Sign in to access Insight Sharing personal library and reading history.',
    emailLabel: 'EMAIL ADDRESS',
    passwordLabel: 'PASSWORD',
    forgotPassword: 'Forgot password?',
    signIn: 'Sign In',
    orContinueWith: 'Or continue with',
    notMember: 'Not a member yet?',
    createAccount: 'Create an account',
    dedicatedTo: 'Dedicated to restoring and sharing the essence of traditional human culture and wisdom.',
    discover: 'Discover',
    organization: 'Organization',
    stayConnected: 'Stay Connected',
    rightsReserved: 'All rights reserved.',
    digitalReader: 'Digital Reader',
    openNewTab: 'Open in new tab',
    size: 'SIZE',
    alreadyMember: 'Already a member?',
    fullName: 'Full Name',
    joinCommunity: 'Join Community',
    joinSub: 'Create an account to personalize your library and save progress.',
    resetPassword: 'Reset Password',
    resetPasswordSub: 'Enter your email address and we\'ll send you a link to reset your password.',
    sendResetLink: 'Send Reset Link',
    backToSignIn: 'Back to Sign In',
    resetSuccess: 'We have sent a password reset link to your email.',
  },
  zh: {
    home: '首页',
    books: '书籍',
    articles: '文章',
    multimedia: '多媒体',
    about: '关于',
    authors: '作者',
    login: '会员',
    donate: '捐助',
    library: '图书馆',
    audioLibrary: '音频库',
    heroSub: '通过 Insight Sharing 精选馆藏，探索五千年文明的精髓。',
    searchPlaceholder: '搜索标题或作者...',
    readOnline: '在线阅读',
    viewDetails: '查看详情',
    totalCollection: '馆藏总量',
    loadMore: '加载更多',
    listenNow: '立即收听',
    contactUs: '联系我们',
    synopsis: '简介',
    bookDetails: '书籍详情',
    aiLibrarian: 'AI 馆员',
    totalTracks: '音轨',
    all: '全部',
    history: '历史',
    philosophy: '哲学',
    culture: '文化',
    arts: '艺术',
    biography: '传记',
    buddhism: '佛家',
    donateHeader: '支持 Insight Sharing',
    donateDesc: '您的捐助将帮助我们保护五千年的智慧，并将其推向全球观众。',
    oneTime: '一次性',
    monthly: '每月',
    customAmount: '自定义金额',
    leaveMessage: '留言（可选）',
    next: '下一步',
    raised: '已筹集',
    goal: '目标',
    backers: '支持者',
    artistProfile: '艺术家详情',
    artistCode: '编号',
    audioAlbums: '音频专辑',
    bookAlbums: '书籍系列',
    videoAlbums: '视频系列',
    totalInteractions: '总播放/阅读',
    mostPopular: '最受欢迎作品',
    audio: '音频',
    videos: '视频',
    none: '暂无数据',
    welcomeBack: '欢迎回来',
    loginSub: '登录以访问您的个人图书馆和阅读历史。',
    emailLabel: '电子邮件地址',
    passwordLabel: '密码',
    forgotPassword: '忘记密码？',
    signIn: '登录',
    orContinueWith: '或通过以下方式继续',
    notMember: '还不是会员？',
    createAccount: '创建账户',
    dedicatedTo: '致力于恢复和分享传统人类文化与智慧的精髓。',
    discover: '发现',
    organization: '组织机构',
    stayConnected: '保持联系',
    rightsReserved: '版权所有。',
    digitalReader: '数字阅读器',
    openNewTab: '在新标签页中打开',
    size: '文件大小',
    alreadyMember: '已经是会员？',
    fullName: '全名',
    joinCommunity: '加入社区',
    joinSub: '创建帐户以个性化您的图书馆并保存进度。',
    resetPassword: '重置密码',
    resetPasswordSub: '输入您的电子邮件地址，我们将向您发送重置密码的链接。',
    sendResetLink: '发送重置链接',
    backToSignIn: '返回登录',
    resetSuccess: '我们已向您的电子邮件发送了重置密码的链接。',
  },
  kh: {
    home: 'ទំព័រដើម',
    books: 'សៀវភៅ',
    articles: 'អត្ថបទ',
    multimedia: 'ពហុព័ត៌មាន',
    about: 'អំពីយើង',
    authors: 'អ្នកនិពន្ធ',
    login: 'សមាជិក',
    donate: 'ឧបត្ថម្ភ',
    library: 'បណ្ណាល័យ',
    audioLibrary: 'បណ្ណាល័យសំឡេង',
    heroSub: 'ស្វែងយល់ពីខ្លឹមសារនៃវប្បធម៌ប្រពៃណី ៥០០០ ឆ្នាំ តាមរយៈ Insight Sharing។',
    searchPlaceholder: 'ស្វែងរកតាមចំណងជើង ឬអ្នកនិពន្ធ...',
    readOnline: 'អានអនឡាញ',
    viewDetails: 'មើលលម្អិត',
    totalCollection: 'ចំនួនសរុប',
    loadMore: 'មើលបន្ថែម',
    listenNow: 'ស្ដាប់ឥឡូវ',
    contactUs: 'ទាក់ទងយើង',
    synopsis: 'សេចក្ដីសង្ខេប',
    bookDetails: 'ព័ត៌មានសៀវភៅ',
    aiLibrarian: 'AI បណ្ណារក្ស',
    totalTracks: 'សំឡេង',
    all: 'ទាំងអស់',
    history: 'ប្រវត្តិសាស្ត្រ',
    philosophy: 'ទស្សនវិជ្ជា',
    culture: 'វប្បធម៌',
    arts: 'សិល្បៈ',
    biography: 'ជីវប្រវត្តិ',
    buddhism: 'ព្រះពុទ្ធសាសនា',
    donateHeader: 'គាំទ្រ Insight Sharing',
    donateDesc: 'ការចូលរួមរបស់អ្នកជួយថែរក្សាប្រាជ្ញារាប់ពាន់ឆ្នាំ និងនាំយកវាទៅកាន់ពិភពលោក។',
    oneTime: 'ម្ដង',
    monthly: 'រាល់ខែ',
    customAmount: 'ចំនួនផ្សេងៗ',
    leaveMessage: 'សារខ្លីៗ (បើមាន)',
    next: 'បន្ទាប់',
    raised: 'ទទួលបាន',
    goal: 'គោលដៅ',
    backers: 'អ្នកគាំទ្រ',
    artistProfile: 'ព័ត៌មានអ្នកសម្តែង',
    artistCode: 'លេខសម្គាល់',
    audioAlbums: 'អាល់ប៊ុម សំឡេង',
    bookAlbums: 'អាល់ប៊ុម សៀវភៅ',
    videoAlbums: 'អាល់ប៊ុម វីដេអូ',
    totalInteractions: 'ចំនួន ស្ដាប់/អាន សរុប',
    mostPopular: 'ស្ដាប់/អាន/ទស្សនា ច្រើនជាងគេ',
    audio: 'សំឡេង',
    videos: 'វីដេអូ',
    none: 'គ្មានទិន្នន័យ',
    welcomeBack: 'សូមស្វាគមន៍មកវិញ',
    loginSub: 'ចូលប្រើដើម្បីទទួលបានបណ្ណាល័យផ្ទាល់ខ្លួន និងប្រវត្តិអានរបស់អ្នក។',
    emailLabel: 'អាសយដ្ឋានអ៊ីមែល',
    passwordLabel: 'ពាក្យសម្ងាត់',
    forgotPassword: 'ភ្លេចពាក្យសម្ងាត់?',
    signIn: 'ចូលប្រើ',
    orContinueWith: 'ឬបន្តជាមួយ',
    notMember: 'មិនទាន់ជាសមាជិក?',
    createAccount: 'បង្កើតគណនី',
    dedicatedTo: 'ឧទ្ទិសដល់ការស្ដារ និងចែករំលែកខ្លឹមសារនៃវប្បធម៌ និងប្រាជ្ញារបស់មនុស្សជាតិ។',
    discover: 'ស្វែងយល់',
    organization: 'ស្ថាប័ន',
    stayConnected: 'បណ្តាញសង្គម',
    rightsReserved: 'រក្សាសិទ្ធិគ្រប់យ៉ាង។',
    digitalReader: 'កម្មវិធីអានឌីជីថល',
    openNewTab: 'បើកក្នុងផ្ទាំងថ្មី',
    size: 'ទំហំឯកសារ',
    alreadyMember: 'ជាសមាជិករួចហើយ?',
    fullName: 'ឈ្មោះ​ពេញ',
    joinCommunity: 'ចូលរួមជាមួយសហគមន៍',
    joinSub: 'បង្កើតគណនីដើម្បីកំណត់បណ្ណាល័យផ្ទាល់ខ្លួន និងរក្សាទុកវឌ្ឍនភាព។',
    resetPassword: 'កំណត់ពាក្យសម្ងាត់ឡើងវិញ',
    resetPasswordSub: 'បញ្ចូលអ៊ីមែលរបស់អ្នក ហើយយើងនឹងផ្ញើតំណដើម្បីកំណត់ពាក្យសម្ងាត់របស់អ្នកឡើងវិញ។',
    sendResetLink: 'ផ្ញើតំណ',
    backToSignIn: 'ត្រឡប់ទៅចូលប្រើ',
    resetSuccess: 'យើងបានផ្ញើតំណកំណត់ពាក្យសម្ងាត់ទៅអ៊ីមែលរបស់អ្នក។',
  }
};
