import { Book, Video, Artist, Audio, Category, Article } from './types';

export const CATEGORIES: Category[] = ['All', 'History', 'Philosophy', 'Culture', 'Arts', 'Biography'];
export const VIDEO_CATEGORIES = ['All', 'Documentary', 'Performance', 'Interview', 'Shorts'];
export const AUDIO_CATEGORIES = ['All', 'Symphony', 'Instrumental', 'Vocal', 'Podcast'];

export const ARTICLES: Article[] = [
  {
    id: '1',
    title: 'The Resonance of Ancient Music',
    titleZh: '古乐的共鸣',
    titleKh: 'សំឡេងនៃតន្ត្រីបុរាណ',
    excerpt: 'Exploring how traditional Chinese musical instruments like the Erhu and Pipa connect modern audiences to the spiritual essence of 5,000 years.',
    excerptZh: '探讨二胡、琵琶等中国传统乐器如何将现代观众与五千年的精神精髓联系在一起。',
    content: 'The sounds of ancient China are not merely notes; they are echoes of a civilization that viewed music as a bridge between the human and the divine. Instruments like the Erhu, with its two strings capable of mimicking the human voice, and the Pipa, known as the king of Chinese instruments, carry within them the melodies of thousands of years.\n\nIn traditional thought, music was used to harmonize the soul and the state. Confucius himself emphasized the importance of ritual and music in creating a stable society. Today, as we listen to these instruments in modern concert halls, we are not just hearing art; we are participating in a spiritual continuity that has survived dynasties and upheavals.\n\nThe unique tonal systems and the emphasis on the "inner spirit" of the performer make Chinese classical music a meditative experience. It requires both the artist and the audience to find a state of stillness, allowing the resonance of the ancient past to speak to the challenges of the modern present.',
    author: 'Elena Wong',
    authorZh: '王艾琳',
    date: '2024-01-15',
    readTime: '8 min',
    imageUrl: 'https://images.unsplash.com/photo-1516280440614-6697288d5d38?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    category: 'Arts',
    views: 3200
  },
  {
    id: '2',
    title: 'Confucian Values in the Digital Age',
    titleZh: '数字时代的儒家价值观',
    titleKh: 'តម្លៃខុងជឺក្នុងយុគសម័យឌីជីថល',
    excerpt: 'Can ancient wisdom regarding filial piety and benevolence guide our interactions in a hyper-connected world?',
    excerptZh: '关于孝道和仁慈的古老智慧能否指导我们在高度互联的世界中的互动？',
    content: 'As we navigate the complexities of social media, artificial intelligence, and global connectivity, the core tenets of Confucianism—Ren (Benevolence), Yi (Righteousness), and Li (Propriety)—remain surprisingly relevant. While the technologies change, the fundamental nature of human relationships does not.\n\nIn the digital age, "Propriety" might be reinterpreted as digital citizenship and ethical online behavior. How we treat others in a space where we are anonymous or physically distant tests our character in ways the ancients might have recognized as the ultimate test of "Junzi" (the exemplary person).\n\nFurthermore, the concept of Filial Piety is evolving. In a world where families are often separated by oceans but connected by video calls, how do we honor the previous generation? Confucianism teaches us that respect is not about physical proximity, but about the sincerity of our intentions and the consistency of our care.',
    author: 'Dr. Liang Chen',
    authorZh: '陈亮博士',
    date: '2024-02-01',
    readTime: '12 min',
    imageUrl: 'https://images.unsplash.com/photo-1524230572899-a752b3835840?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    category: 'Philosophy',
    views: 4500
  },
  {
    id: '3',
    title: 'The Hidden History of Silk Road Murals',
    titleZh: '丝绸之路壁画背后隐藏的历史',
    titleKh: 'ប្រវត្តិសាស្រ្តអាថ៌កំបាំងនៃផ្ទាំងគំនូរលើជញ្ជាំងផ្លូវសូត្រ',
    excerpt: 'A deep dive into the artistic techniques and religious symbols found in the Dunhuang caves.',
    excerptZh: '深入研究敦煌石窟中发现的艺术技巧和宗教符号。',
    content: 'The Mogao Caves in Dunhuang are more than just a gallery of religious art; they are a visual encyclopedia of a millennium of cultural exchange. The murals found within these caves tell stories of merchants, monks, and monarchs from across the Eurasian continent.\n\nTechnically, the murals represent a pinnacle of ancient fresco painting. The use of mineral pigments has allowed the colors to remain vibrant for over a thousand years. Artists blended styles from India, Persia, and Central Asia with traditional Chinese techniques, creating a unique aesthetic that defined the "Dunhuang Style".\n\nBeyond their beauty, these murals provide critical insights into the daily life, fashion, and social structures of the Tang and Song dynasties. They show us that the Silk Road was not just a path for silk and spices, but a grand highway for ideas and spiritual transformation.',
    author: 'Sophia Martelli',
    authorZh: '索菲亚·马特利',
    date: '2023-12-20',
    readTime: '15 min',
    imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    category: 'History',
    views: 2800
  },
  {
    id: '4',
    title: 'The Way of Tea: More Than a Drink',
    titleZh: '茶道：不只是饮品',
    titleKh: 'វិថីនៃតែ៖ ច្រើនជាងភេសជ្ជៈ',
    excerpt: 'How the simple act of preparing tea became a profound spiritual practice emphasizing harmony, respect, and tranquility.',
    excerptZh: '泡茶的简单行为如何成为一种强调和谐、尊重和宁静的深刻精神实践。',
    author: 'Master Yuki',
    authorZh: '结城大师',
    date: '2024-02-10',
    readTime: '10 min',
    imageUrl: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    category: 'Culture',
    views: 1900
  },
  {
    id: '5',
    title: 'Calligraphy: The Dance of the Brush',
    titleZh: '书法：笔尖的舞蹈',
    titleKh: 'សិល្បៈអក្សរផ្ចង់៖ របាំនៃជក់',
    excerpt: 'Understanding the dynamic energy and meditative focus required for traditional brushwork.',
    excerptZh: '了解传统笔法所需的动态能量和冥想焦点。',
    author: 'Lin Wei',
    authorZh: '林伟',
    date: '2024-02-15',
    readTime: '6 min',
    imageUrl: 'https://images.unsplash.com/photo-1508807526345-15e9b5f4eaff?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    category: 'Arts',
    views: 5200
  },
  {
    id: '6',
    title: 'Engineering the Great Wall',
    titleZh: '长城的工程奇迹',
    titleKh: 'វិស្វកម្មមហាកំពែង',
    excerpt: 'An investigation into the architectural marvels and military strategies that built the world\'s longest fortification.',
    excerptZh: '调查建造世界上最长防御工事的建筑奇迹和军事战略。',
    author: 'Dr. James Miller',
    authorZh: '詹姆斯·米勒博士',
    date: '2023-11-28',
    readTime: '20 min',
    imageUrl: 'https://images.unsplash.com/photo-1508804185872-d7badad00f7d?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    category: 'History',
    views: 7400
  },
  {
    id: '7',
    title: 'Mencius and the Heart of Compassion',
    titleZh: '孟子与恻隐之心',
    titleKh: 'ម៉េងជឺ និងបេះដូងនៃសេចក្ដីមេត្តា',
    excerpt: 'Exploring the philosophical foundation of human goodness in the teachings of the "Second Sage".',
    excerptZh: '探索“亚圣”教义中人性善的哲学基础。',
    author: 'Professor Zhang',
    authorZh: '张教授',
    date: '2024-03-01',
    readTime: '14 min',
    imageUrl: 'https://images.unsplash.com/photo-1524230572899-a752b3835840?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    category: 'Philosophy',
    views: 3100
  },
  {
    id: '8',
    title: 'Poetry of the Tang Dynasty',
    titleZh: '唐诗的魅力',
    titleKh: 'កំណាព្យសម័យរាជវង្សថាង',
    excerpt: 'Why the golden age of Chinese poetry still resonates with emotional depth over a thousand years later.',
    excerptZh: '为什么中国诗歌的黄金时代在一千多年后仍然引起情感共鸣。',
    author: 'Sarah Jenkins',
    authorZh: '莎拉·詹金斯',
    date: '2024-01-05',
    readTime: '11 min',
    imageUrl: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    category: 'Arts',
    views: 4800
  },
  {
    id: '9',
    title: 'The Lunar New Year: A Cosmic Renewal',
    titleZh: '农历新年：宇宙的更新',
    titleKh: 'បុណ្យចូលឆ្នាំថ្មី៖ ការផ្លាស់ប្តូរថ្មីនៃចក្រវាល',
    excerpt: 'Tracing the astronomical and cultural roots of the most important traditional holiday.',
    excerptZh: '追溯最重要的传统节日的天文学和文化根源。',
    author: 'Li Ming',
    authorZh: '李明',
    date: '2024-02-05',
    readTime: '9 min',
    imageUrl: 'https://images.unsplash.com/photo-1543157145-f78c636d023d?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    category: 'Culture',
    views: 9200
  },
  {
    id: '10',
    title: 'Architecture of the Forbidden City',
    titleZh: '故宫建筑的象征意义',
    titleKh: 'ស្ថាបត្យកម្មនៃបុរីហាមឃាត់',
    excerpt: 'How the design of the Imperial Palace reflects the ancient Chinese understanding of the heavens and earth.',
    excerptZh: '皇宫的设计如何反映中国古代对天地的理解。',
    author: 'Arthur Chen',
    authorZh: '亚瑟·陈',
    date: '2023-10-12',
    readTime: '18 min',
    imageUrl: 'https://images.unsplash.com/photo-1547981609-4b6bfe67ca0b?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    category: 'History',
    views: 6100
  },
  {
    id: '11',
    title: 'The Wisdom of Traditional Medicine',
    titleZh: '传统医学的智慧',
    titleKh: 'ប្រាជ្ញានៃឱសថបុរាណ',
    excerpt: 'Understanding the balance of Yin and Yang in holistic health and longevity.',
    excerptZh: '了解整体健康和长寿中阴阳的平衡。',
    author: 'Dr. Zhao',
    authorZh: '赵医生',
    date: '2023-12-01',
    readTime: '13 min',
    imageUrl: 'https://images.unsplash.com/photo-1512069772995-ec65ed45afd6?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    category: 'Culture',
    views: 3900
  },
  {
    id: '12',
    title: 'Li Bai: The Immortal Poet',
    titleZh: '李白：诗仙的传奇',
    titleKh: 'លី ប៉ៃ៖ កំពូលកវីអមតៈ',
    excerpt: 'A biographical sketch of China\'s most beloved poet and his journey through mountains and wine.',
    excerptZh: '中国最受喜爱的诗人的传记小传，以及他在山水和美酒中的旅程。',
    author: 'Cultural Heritage Team',
    authorZh: '文化遗产团队',
    date: '2023-09-20',
    readTime: '16 min',
    imageUrl: 'https://images.unsplash.com/photo-1522770179533-24471fcdba45?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    category: 'Biography',
    views: 8800
  }
];

export const BOOKS: Book[] = [
  {
    id: '1',
    title: 'The Analects',
    titleZh: '论语',
    titleKh: 'អាណាលេក',
    author: 'Confucius',
    authorZh: '孔子',
    authorKh: 'ខុងជឺ',
    category: 'Philosophy',
    categoryZh: '哲学',
    year: '475 BC',
    coverUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Confucius_Analects_Project_Gutenberg.jpg/300px-Confucius_Analects_Project_Gutenberg.jpg',
    description: 'A collection of sayings and ideas attributed to the Chinese philosopher Confucius.',
    descriptionZh: '记录孔子及其弟子言行的语录集。',
    pages: 350,
    publisher: 'Classic Press',
    views: 12500,
    fileSize: '4.5 MB'
  },
  {
    id: '2',
    title: 'Tao Te Ching',
    titleZh: '道德经',
    titleKh: 'តាវតឺជីង',
    author: 'Laozi',
    authorZh: '老子',
    authorKh: 'ឡៅជឺ',
    category: 'Philosophy',
    categoryZh: '哲学',
    year: '400 BC',
    coverUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Lao_Tzu_-_Project_Gutenberg_eText_15606.jpg/300px-Lao_Tzu_-_Project_Gutenberg_eText_15606.jpg',
    description: 'A fundamental text for both philosophical and religious Taoism.',
    descriptionZh: '道家哲学思想的重要来源。',
    pages: 81,
    publisher: 'Ancient Wisdom',
    views: 9800,
    fileSize: '2.1 MB'
  },
  {
    id: '3',
    title: 'Records of the Grand Historian',
    titleZh: '史记',
    titleKh: 'កំណត់ត្រាប្រវត្តិសាស្ត្រ',
    author: 'Sima Qian',
    authorZh: '司马迁',
    authorKh: 'ស៊ីម៉ា ឈាន',
    category: 'History',
    categoryZh: '历史',
    year: '94 BC',
    coverUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Sima_Qian.jpg/300px-Sima_Qian.jpg',
    description: 'A monumental history of ancient China and the world.',
    descriptionZh: '中国历史上第一部纪传体通史。',
    pages: 2000,
    publisher: 'Han Dynasty Archives',
    views: 15400,
    fileSize: '15.8 MB'
  },
  {
    id: '4',
    title: 'Dream of the Red Chamber',
    titleZh: '红楼梦',
    titleKh: 'សុបិន្តនៃវិមានក្រហម',
    author: 'Cao Xueqin',
    authorZh: '曹雪芹',
    authorKh: 'ឆាវ ស៊ូឈិន',
    category: 'Arts',
    categoryZh: '艺术',
    year: '1791',
    coverUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Dream_of_the_Red_Chamber.jpg/300px-Dream_of_the_Red_Chamber.jpg',
    description: 'A masterpiece of Chinese literature, one of the Four Great Classical Novels.',
    descriptionZh: '中国古典四大名著之首。',
    pages: 1200,
    publisher: 'Qing Dynasty Press',
    views: 22100,
    fileSize: '8.9 MB'
  },
  {
    id: '5',
    title: 'The Art of War',
    titleZh: '孙子兵法',
    titleKh: 'សិល្បៈសង្គ្រាម',
    author: 'Sun Tzu',
    authorZh: '孙武',
    authorKh: 'ស៊ុន ជឺ',
    category: 'Philosophy',
    categoryZh: '哲学',
    year: '5th Century BC',
    coverUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Bamboo_book_-_binding_-_UCR.jpg/300px-Bamboo_book_-_binding_-_UCR.jpg',
    description: 'An ancient Chinese military treatise attributed to Sun Tzu.',
    descriptionZh: '世界上最早的兵书之一。',
    pages: 50,
    publisher: 'Military Classics',
    views: 30500,
    fileSize: '1.5 MB'
  },
  {
    id: '6',
    title: 'Yellow Emperor\'s Inner Canon',
    titleZh: '黄帝内经',
    titleKh: 'គម្ពីរពេទ្យបុរាណចិន',
    author: 'Unknown',
    authorZh: '佚名',
    authorKh: 'មិនស្ស្គាល់',
    category: 'Culture',
    categoryZh: '文化',
    year: '200 BC',
    coverUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Huangdi_Neijing.jpg/300px-Huangdi_Neijing.jpg',
    description: 'The fundamental doctrinal source for Chinese medicine.',
    descriptionZh: '中医理论的奠基之作。',
    pages: 600,
    publisher: 'Traditional Medicine Press',
    views: 8700,
    fileSize: '5.2 MB'
  },
  {
    id: '7',
    title: 'Journey to the West',
    titleZh: '西游记',
    titleKh: 'ដំណើរទៅទិសខាងលិច',
    author: 'Wu Cheng\'en',
    authorZh: '吴承恩',
    authorKh: 'អ៊ូ ឆឹងអ៊ិន',
    category: 'Arts',
    categoryZh: '艺术',
    year: '1592',
    coverUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Journey_to_the_West.jpg/300px-Journey_to_the_West.jpg',
    description: 'A Chinese novel published in the 16th century during the Ming dynasty.',
    descriptionZh: '中国神魔小说的经典之作。',
    pages: 1500,
    publisher: 'Ming Press',
    views: 45000,
    fileSize: '10.1 MB'
  },
  {
    id: '8',
    title: 'Compendium of Materia Medica',
    titleZh: '本草纲目',
    titleKh: 'ឱសថបុរាណចិន',
    author: 'Li Shizhen',
    authorZh: '李时珍',
    authorKh: 'លី ស៊ីជេន',
    category: 'Culture',
    categoryZh: '文化',
    year: '1578',
    coverUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Bencao_Gangmu.jpg/300px-Bencao_Gangmu.jpg',
    description: 'A pharmaceutical text written by Li Shizhen during the Ming dynasty.',
    descriptionZh: '集中国古代医药学之大成的著作。',
    pages: 2000,
    publisher: 'Medical Heritage',
    views: 6500,
    fileSize: '18.4 MB'
  }
];

export const AUDIOS: Audio[] = [
  {
    id: '1',
    title: 'Divine Mercy',
    titleZh: '慈悲的展现',
    titleKh: 'សេចក្តីមេត្តាករុណា',
    artist: 'Shen Yun Symphony Orchestra',
    artistZh: '神韵交响乐团',
    artistKh: 'វង់ភ្លេង Shen Yun',
    category: 'Symphony',
    categoryZh: '交响乐',
    coverUrl: 'https://www.shenyunshop.com/cdn/shop/products/CD_2017_Symphony_600x.jpg?v=1510258001',
    duration: '04:15',
    date: '2023-10-15',
    plays: 5420,
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3'
  },
  {
    id: '2',
    title: 'The Warriors of Wudang Mountain',
    titleZh: '武当勇士',
    titleKh: 'អ្នកប្រយុទ្ធវូដាំង',
    artist: 'Shen Yun Symphony Orchestra',
    artistZh: '神韵交响乐团',
    artistKh: 'វង់ភ្លេង Shen Yun',
    category: 'Instrumental',
    categoryZh: '器乐',
    coverUrl: 'https://www.shenyunshop.com/cdn/shop/products/CD_2013_Symphony_600x.jpg?v=1510257545',
    duration: '03:45',
    date: '2023-09-20',
    plays: 3200,
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3'
  },
  {
    id: '3',
    title: 'Plum Blossom',
    titleZh: '梅花',
    titleKh: 'ផ្កាអង្គារសីល',
    artist: 'Traditional Ensemble',
    artistZh: '传统乐团',
    artistKh: 'ក្រុមភ្លេងបុរាណ',
    category: 'Vocal',
    categoryZh: '声乐',
    coverUrl: 'https://images.unsplash.com/photo-1516280440614-6697288d5d38?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
    duration: '05:10',
    date: '2023-08-05',
    plays: 1800,
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3'
  }
];

export const VIDEOS: Video[] = [
  {
    id: '1',
    title: 'Understanding Traditional Culture',
    titleZh: '理解传统文化',
    titleKh: 'ស្វែងយល់ពីវប្បធម៌ប្រពៃណី',
    thumbnailUrl: 'https://images.unsplash.com/photo-1514533240710-2856035caee9?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    duration: '15:30',
    category: 'Documentary',
    categoryZh: '纪录片',
    views: 12000,
    date: '2023-11-01',
    presenter: 'Prof. Zhang',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4'
  },
  {
    id: '2',
    title: 'Classical Chinese Dance Training',
    titleZh: '中国古典舞训练',
    titleKh: 'ការហ្វឹកហាត់របាំបុរាណចិន',
    thumbnailUrl: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    duration: '08:45',
    category: 'Performance',
    categoryZh: '表演',
    views: 8500,
    date: '2023-10-20',
    presenter: 'Li Bo',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4'
  },
  {
    id: '3',
    title: 'Interview with a Historian',
    titleZh: '历史学家访谈',
    titleKh: 'កិច្ចសម្ភាសន៍ជាមួយអ្នកប្រវត្តិសាស្ត្រ',
    thumbnailUrl: 'https://images.unsplash.com/photo-1551817958-c9664f3d135d?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    duration: '22:15',
    category: 'Interview',
    categoryZh: '访谈',
    views: 5600,
    date: '2023-09-15',
    presenter: 'Sarah Chen',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4'
  }
];

export const ARTIST_PROFILES: Artist[] = [
  {
    id: '1',
    name: 'Shen Yun Symphony Orchestra',
    nameZh: '神韵交响乐团',
    nameKh: 'វង់ភ្លេង Shen Yun',
    role: 'Orchestra',
    roleZh: '乐团',
    roleKh: 'វង់ភ្លេង',
    bio: 'The Shen Yun Symphony Orchestra blends the spirit of Chinese music with the power of a Western orchestra. It features ancient Chinese instruments like the erhu and pipa leading the melody on top of a full orchestra.',
    bioZh: '神韵交响乐团将中国音乐的精神与西方交响乐团的宏大完美结合。以二胡、琵琶等古老中国乐器领奏，西方管弦乐团伴奏。',
    imageUrl: 'https://www.shenyunshop.com/cdn/shop/products/CD_2017_Symphony_600x.jpg?v=1510258001',
    code: 'SYSO',
  },
  {
    id: '2',
    name: 'Confucius',
    nameZh: '孔子',
    nameKh: 'ខុងជឺ',
    role: 'Philosopher',
    roleZh: '哲学家',
    roleKh: 'ទស្សនវិទូ',
    bio: 'Confucius was a Chinese philosopher and politician of the Spring and Autumn period. The philosophy of Confucius, also known as Confucianism, emphasized personal and governmental morality, correctness of social relationships, justice, kindness, and sincerity.',
    bioZh: '孔子是春秋时期的中国哲学家和政治家。孔子的哲学，即儒家思想，强调个人和政府的道德、社会关系的正确性、正义、仁慈和真诚。',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Confucius_Analects_Project_Gutenberg.jpg/300px-Confucius_Analects_Project_Gutenberg.jpg',
    code: 'CF',
  },
  {
    id: '3',
    name: 'Li Bo',
    nameZh: '李博',
    nameKh: 'លី បូ',
    role: 'Dancer',
    roleZh: '舞蹈家',
    roleKh: 'អ្នករាំ',
    bio: 'Li Bo is a principal dancer with Shen Yun Performing Arts. He is known for his high-flying techniques and expressive portrayal of characters from Chinese history and mythology.',
    bioZh: '李博是神韵艺术团的领舞演员。他以高超的技巧和对中国历史和神话人物的生动刻画而闻名。',
    imageUrl: 'https://images.unsplash.com/photo-1542596594-649edbc13630?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
    code: 'LB',
  }
];

export const UI_STRINGS = {
  en: {
    home: 'Home',
    books: 'Books',
    articles: 'Articles',
    multimedia: 'Multimedia',
    about: 'About',
    authors: 'Authors',
    login: 'Member',
    donate: 'Donate',
    library: 'Library',
    audioLibrary: 'Audio Library',
    heroSub: 'Discovering the essence of 5000 years of civilization, history, and wisdom through Insight Sharing.',
    searchPlaceholder: 'Search by title or author...',
    readOnline: 'READ ONLINE',
    viewDetails: 'View Details',
    totalCollection: 'Total Collection',
    loadMore: 'Load More',
    listenNow: 'Listen Now',
    contactUs: 'Contact Us',
    synopsis: 'Synopsis',
    bookDetails: 'Book Details',
    aiLibrarian: 'AI Librarian',
    totalTracks: 'Tracks',
    all: 'All',
    history: 'History',
    philosophy: 'Philosophy',
    culture: 'Culture',
    arts: 'Arts',
    biography: 'Biography',
    donateHeader: 'Support Insight Sharing',
    donateDesc: 'Your contribution helps us preserve five millennia of wisdom and bring it to a global audience.',
    oneTime: 'One-time',
    monthly: 'Monthly',
    customAmount: 'Custom Amount',
    leaveMessage: 'Leave a message (Optional)',
    next: 'Next',
    raised: 'Raised',
    goal: 'Goal',
    backers: 'Backers',
    artistProfile: 'Artist Profile',
    artistCode: 'Code',
    audioAlbums: 'Audio Albums',
    bookAlbums: 'Book Collections',
    videoAlbums: 'Video Collections',
    totalInteractions: 'Total Plays/Reads',
    mostPopular: 'Most Popular Contributions',
    audio: 'Audio',
    videos: 'Videos',
    none: 'None available',
    welcomeBack: 'Welcome Back',
    loginSub: 'Sign in to access Insight Sharing personal library and reading history.',
    emailLabel: 'EMAIL ADDRESS',
    passwordLabel: 'PASSWORD',
    forgotPassword: 'Forgot password?',
    signIn: 'Sign In',
    orContinueWith: 'Or continue with',
    notMember: 'Not a member yet?',
    createAccount: 'Create an account',
    dedicatedTo: 'Dedicated to restoring and sharing the essence of traditional human culture and wisdom.',
    discover: 'Discover',
    organization: 'Organization',
    stayConnected: 'Stay Connected',
    rightsReserved: 'All rights reserved.',
    digitalReader: 'Digital Reader',
    openNewTab: 'Open in new tab',
    size: 'SIZE',
    alreadyMember: 'Already a member?',
    fullName: 'Full Name',
    joinCommunity: 'Join Community',
    joinSub: 'Create an account to personalize your library and save progress.',
    resetPassword: 'Reset Password',
    resetPasswordSub: 'Enter your email address and we\'ll send you a link to reset your password.',
    sendResetLink: 'Send Reset Link',
    backToSignIn: 'Back to Sign In',
    resetSuccess: 'We have sent a password reset link to your email.',
  },
  zh: {
    home: '首页',
    books: '书籍',
    articles: '文章',
    multimedia: '多媒体',
    about: '关于',
    authors: '作者',
    login: '会员',
    donate: '捐助',
    library: '图书馆',
    audioLibrary: '音频库',
    heroSub: '通过 Insight Sharing 精选馆藏，探索五千年文明的精髓。',
    searchPlaceholder: '搜索标题或作者...',
    readOnline: '在线阅读',
    viewDetails: '查看详情',
    totalCollection: '馆藏总量',
    loadMore: '加载更多',
    listenNow: '立即收听',
    contactUs: '联系我们',
    synopsis: '简介',
    bookDetails: '书籍详情',
    aiLibrarian: 'AI 馆员',
    totalTracks: '音轨',
    all: '全部',
    history: '历史',
    philosophy: '哲学',
    culture: '文化',
    arts: '艺术',
    biography: '传记',
    donateHeader: '支持 Insight Sharing',
    donateDesc: '您的捐助将帮助我们保护五千年的智慧，并将其推向全球观众。',
    oneTime: '一次性',
    monthly: '每月',
    customAmount: '自定义金额',
    leaveMessage: '留言（可选）',
    next: '下一步',
    raised: '已筹集',
    goal: '目标',
    backers: '支持者',
    artistProfile: '艺术家详情',
    artistCode: '编号',
    audioAlbums: '音频专辑',
    bookAlbums: '书籍系列',
    videoAlbums: '视频系列',
    totalInteractions: '总播放/阅读',
    mostPopular: '最受欢迎作品',
    audio: '音频',
    videos: '视频',
    none: '暂无数据',
    welcomeBack: '欢迎回来',
    loginSub: '登录以访问您的个人图书馆和阅读历史。',
    emailLabel: '电子邮件地址',
    passwordLabel: '密码',
    forgotPassword: '忘记密码？',
    signIn: '登录',
    orContinueWith: '或通过以下方式继续',
    notMember: '还不是会员？',
    createAccount: '创建账户',
    dedicatedTo: '致力于恢复和分享传统人类文化与智慧的精髓。',
    discover: '发现',
    organization: '组织机构',
    stayConnected: '保持联系',
    rightsReserved: '版权所有。',
    digitalReader: '数字阅读器',
    openNewTab: '在新标签页中打开',
    size: '文件大小',
    alreadyMember: '已经是会员？',
    fullName: '全名',
    joinCommunity: '加入社区',
    joinSub: '创建帐户以个性化您的图书馆并保存进度。',
    resetPassword: '重置密码',
    resetPasswordSub: '输入您的电子邮件地址，我们将向您发送重置密码的链接。',
    sendResetLink: '发送重置链接',
    backToSignIn: '返回登录',
    resetSuccess: '我们已向您的电子邮件发送了重置密码的链接。',
  },
  kh: {
    home: 'ទំព័រដើម',
    books: 'សៀវភៅ',
    articles: 'អត្ថបទ',
    multimedia: 'ពហុព័ត៌មាន',
    about: 'អំពីយើង',
    authors: 'អ្នកនិពន្ធ',
    login: 'សមាជិក',
    donate: 'ឧបត្ថម្ភ',
    library: 'បណ្ណាល័យ',
    audioLibrary: 'បណ្ណាល័យសំឡេង',
    heroSub: 'ស្វែងយល់ពីខ្លឹមសារនៃវប្បធម៌ប្រពៃណី ៥០០០ ឆ្នាំ តាមរយៈ Insight Sharing។',
    searchPlaceholder: 'ស្វែងរកតាមចំណងជើង ឬអ្នកនិពន្ធ...',
    readOnline: 'អានអនឡាញ',
    viewDetails: 'មើលលម្អិត',
    totalCollection: 'ចំនួនសរុប',
    loadMore: 'មើលបន្ថែម',
    listenNow: 'ស្ដាប់ឥឡូវ',
    contactUs: 'ទាក់ទងយើង',
    synopsis: 'សេចក្ដីសង្ខេប',
    bookDetails: 'ព័ត៌មានសៀវភៅ',
    aiLibrarian: 'AI បណ្ណារក្ស',
    totalTracks: 'សំឡេង',
    all: 'ទាំងអស់',
    history: 'ប្រវត្តិសាស្ត្រ',
    philosophy: 'ទស្សនវិជ្ជា',
    culture: 'វប្បធម៌',
    arts: 'សិល្បៈ',
    biography: 'ជីវប្រវត្តិ',
    donateHeader: 'គាំទ្រ Insight Sharing',
    donateDesc: 'ការចូលរួមរបស់អ្នកជួយថែរក្សាប្រាជ្ញារាប់ពាន់ឆ្នាំ និងនាំយកវាទៅកាន់ពិភពលោក។',
    oneTime: 'ម្ដង',
    monthly: 'រាល់ខែ',
    customAmount: 'ចំនួនផ្សេងៗ',
    leaveMessage: 'សារខ្លីៗ (បើមាន)',
    next: 'បន្ទាប់',
    raised: 'ទទួលបាន',
    goal: 'គោលដៅ',
    backers: 'អ្នកគាំទ្រ',
    artistProfile: 'ព័ត៌មានអ្នកសម្តែង',
    artistCode: 'លេខសម្គាល់',
    audioAlbums: 'អាល់ប៊ុម សំឡេង',
    bookAlbums: 'អាល់ប៊ុម សៀវភៅ',
    videoAlbums: 'អាល់ប៊ុម វីដេអូ',
    totalInteractions: 'ចំនួន ស្ដាប់/អាន សរុប',
    mostPopular: 'ស្ដាប់/អាន/ទស្សនា ច្រើនជាងគេ',
    audio: 'សំឡេង',
    videos: 'វីដេអូ',
    none: 'គ្មានទិន្នន័យ',
    welcomeBack: 'សូមស្វាគមន៍មកវិញ',
    loginSub: 'ចូលប្រើដើម្បីទទួលបានបណ្ណាល័យផ្ទាល់ខ្លួន និងប្រវត្តិអានរបស់អ្នក។',
    emailLabel: 'អាសយដ្ឋានអ៊ីមែល',
    passwordLabel: 'ពាក្យសម្ងាត់',
    forgotPassword: 'ភ្លេចពាក្យសម្ងាត់?',
    signIn: 'ចូលប្រើ',
    orContinueWith: 'ឬបន្តជាមួយ',
    notMember: 'មិនទាន់ជាសមាជិក?',
    createAccount: 'បង្កើតគណនី',
    dedicatedTo: 'ឧទ្ទិសដល់ការស្ដារ និងចែករំលែកខ្លឹមសារនៃវប្បធម៌ និងប្រាជ្ញារបស់មនុស្សជាតិ។',
    discover: 'ស្វែងយល់',
    organization: 'ស្ថាប័ន',
    stayConnected: 'បណ្តាញសង្គម',
    rightsReserved: 'រក្សាសិទ្ធិគ្រប់យ៉ាង។',
    digitalReader: 'កម្មវិធីអានឌីជីថល',
    openNewTab: 'បើកក្នុងផ្ទាំងថ្មី',
    size: 'ទំហំឯកសារ',
    alreadyMember: 'ជាសមាជិករួចហើយ?',
    fullName: 'ឈ្មោះ​ពេញ',
    joinCommunity: 'ចូលរួមជាមួយសហគមន៍',
    joinSub: 'បង្កើតគណនីដើម្បីកំណត់បណ្ណាល័យផ្ទាល់ខ្លួន និងរក្សាទុកវឌ្ឍនភាព។',
    resetPassword: 'កំណត់ពាក្យសម្ងាត់ឡើងវិញ',
    resetPasswordSub: 'បញ្ចូលអ៊ីមែលរបស់អ្នក ហើយយើងនឹងផ្ញើតំណដើម្បីកំណត់ពាក្យសម្ងាត់របស់អ្នកឡើងវិញ។',
    sendResetLink: 'ផ្ញើតំណ',
    backToSignIn: 'ត្រឡប់ទៅចូលប្រើ',
    resetSuccess: 'យើងបានផ្ញើតំណកំណត់ពាក្យសម្ងាត់ទៅអ៊ីមែលរបស់អ្នក។',
  }
};